// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvnXALNvYyuq2uYSFdjgkwCKyOHz4yhag',
    appId: '1:334029051696:web:09b0d757d9fd4ec4345af5',
    messagingSenderId: '334029051696',
    projectId: 'connectx-f817a',
    authDomain: 'connectx-f817a.firebaseapp.com',
    storageBucket: 'connectx-f817a.appspot.com',
    measurementId: 'G-5T0PHJRW84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB800O047Jw-h53nfkHGGSOs6QqxeGIc1Y',
    appId: '1:334029051696:android:2028bc7dfec4523b345af5',
    messagingSenderId: '334029051696',
    projectId: 'connectx-f817a',
    storageBucket: 'connectx-f817a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7LZZw4USEc4EKBxBguNdie285gp9QjJA',
    appId: '1:334029051696:ios:445495e4f18433ad345af5',
    messagingSenderId: '334029051696',
    projectId: 'connectx-f817a',
    storageBucket: 'connectx-f817a.appspot.com',
    androidClientId: '334029051696-6fopcmvkgjtj79dqhqrujhrn84l0a791.apps.googleusercontent.com',
    iosClientId: '334029051696-6np6pb70a2a508ide9pob1qhqhmunvnc.apps.googleusercontent.com',
    iosBundleId: 'com.innovio.connectx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7LZZw4USEc4EKBxBguNdie285gp9QjJA',
    appId: '1:334029051696:ios:62f6e55562935892345af5',
    messagingSenderId: '334029051696',
    projectId: 'connectx-f817a',
    storageBucket: 'connectx-f817a.appspot.com',
    androidClientId: '334029051696-6fopcmvkgjtj79dqhqrujhrn84l0a791.apps.googleusercontent.com',
    iosClientId: '334029051696-7q5rdk89ipq6s4mih5u7e1ie1a690ad7.apps.googleusercontent.com',
    iosBundleId: 'com.innovio.connectx.RunnerTests',
  );
}
